### ISSUE TITLE
Merge of devel introduced several potential SEGV

### ISSUE THREAD

**Issue by msalle** [gridcf/UberFTP#11]
The merged commit https://github.com/gridcf/UberFTP/commit/1f28d62f2e688d0a4bfc89a754dfdf3424ef9ed7 introduces several potential SEGV situations.

Lines [3459-3473 in ftp.c](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3459-L3473) have several issues which can result in SEGV in case `strc` doesn't contain a '(', but is for example `"200 Passive delayed.\r\n"` (see below):
1. Around line 3464:
    - in line then sets `ptr` to point at the '\n'
    - line 3461 moves `ptr` to the '\0'
    - line 3463 `delim` becomes 0
    - line 3464 `ptr` is moved beyond the end of the string.
    - using then `ptr` in line 3471 can potentially result in a SEGV
1. Around lines 3471-3473:
    - If `delim` is 0, `strchr()` will typically return the position the terminating '\0' instead of NULL, see `man 3 strchr` under "RETURN VALUE". This means we never hit the `break` in 3471 but instead have `ptr` to point to that terminating '\0'
    - line 3473 then moves `ptr` beyond the end of the string
    - upon the next `strchr()` in the loop we can hit again a SEGV.
    - alternatively, since 1. already put `ptr` beyond the end, the `strchr()` with `delim==0` can get anywhere and `token[]` in line 3470 is filled with garbage from beyond the end of the string, resulting in random SEGV elsewhere.

This can be reproduced e.g. by enabling "passive delayed" mode from the client: After connection enter   
 `quote "OPTS PASV AllowDelayed=1"`
and do an `ls`. At that point the value of `strc` in [ftp.c line 3457](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3457) becomes `"200 Passive delayed.\r\n"`.

EDIT: changed lines selected in link from `#L3471-L3473` to `#L3459-L3473` (fscheiner)

**Comment by fscheiner** [comment]
@msalle:
Apart from seemingly no support for delayed passive in UberFTP, I assume the problem arises from trying to support both EPSV and SPAS at the same time.

I don't know how a response to SPAS would look with IPv6 addresses, with IPv4 addresses it looks like this:
```
229-Entering Striped Passive Mode.
 192,168,0,1,80,33
 192,168,0,2,87,167
 192,168,0,3,96,240
 192,168,0,4,81,83
229 End
```
...so is multi-line, which seems to explain lines 3457 and 3458. I.e. "if there's no opening brace, it must be a response to SPAS, so continue processing from the next line in the response". 

Maybe a check after line 3458 if the first `\n` is actually the end of the response string (true for your example response string above) and then ~"erroring" out~ returning `0` (see lines [3159](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3159) and [3344](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3344) ) could help avoid this situation?

**Comment by fscheiner** [comment]
Another idea could be to examine the response code: if it's not 229 (response code for response to EPSV and SPAS), stop processing and also return `0`from `_f_parse_addrs()`, though that would not really "match" the messages in lines [3165](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3165) and [3350](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3350) (`"No addresses found in %s response:\n%s"`) as a search doesn't happen.

**Comment by msalle** [comment]
Hmm, there is really a lot of things wrong with this block of code. I started to try to fix some bits, but I have the problem that I don't really know the expected response in the different cases.
Ok after re-reading parts of RFC2428, I have some better idea, but it still looks horribly broken... )-: To be precise, the parsing would kind of work with something like https://tools.ietf.org/html/rfc2428#section-2 or https://tools.ietf.org/html/rfc2428#section-3 but your answer does not seem to have any delimiter character in it, not a protocol?! Am I missing something?

**Comment by fscheiner** [comment]
> Hmm, there is really a lot of things wrong with this block of code. I started to try to fix some bits, but I have the problem that I don't really know the expected response in the different cases.
> Ok after re-reading parts of RFC2428, I have some better idea, but it still looks horribly broken... )-:

Well, apparently it seems to work for the standard cases:

* (A) both with strict RFC2428 responses to EPSV (i.e. `(|||<TCP-PORT>|)`) and the much more useful EPSV reponses (i.e. `(|<ADDRESS-FAMILY>|<NET-ADDR>|<TCP-PORT>|)`) a GCT Globus GridFTP server - with `epsv_ip 1` (and possibly `epsv_match 1`) configured - provides

* (B) for PASV

...and (C) not sure for SPAS (see below). But the SPAS case is only relevant for 3rd party transfers IIUC, which is not the predominant use case for UberFTP in my eyes.

> To be precise, the parsing would kind of work with something like https://tools.ietf.org/html/rfc2428#section-2 or https://tools.ietf.org/html/rfc2428#section-3 but your answer does not seem to have any delimiter character in it, not a protocol?! Am I missing something?

The existence of an opening brace `(` in the response determines how the response is processed. (1) If it's not there (like in my example from https://github.com/gridcf/UberFTP/issues/11#issuecomment-690479503), the response is evaluated to be a response to SPAS, (2) if it's there (e.g. `229 Entering Extended Passive Mode (|||12345|)`), the response is evaluated to be a response to EPSV. 

I didn't check every line of code for my first comment, so my example repsonse to SPAS could be somewhat misleading. But this is how it looks for IPv4 addresses. And I assumed that the code will handle such responses differently.

But the code in `ftp.c` actually seems to expect that each address line in a SPAS response looks like the data part of a response to EPSV, i.e. like so: `|<ADDRESS-FAMILY>|<NET-ADDR>|<TCP-PORT>|` (w/o braces around them as it is in a response to EPSV!)). Which is **not** the case in reality. It's only the case when IPv6 addresses are used when doing striping.

Indeed it's arguable why the Globus developers didn't use only the RFC2428 format (which is address family agnostic) for SPAS/SPOR instead of using the "old" format (see page 8 in https://www.ogf.org/documents/GFD.20.pdf) when IPv4 addresses are used and the RFC2428 format when IPv6 addresses are used (see [/gridftp/server-lib/src/globus_gridftp_server_control_commands.c](https://github.com/gridcf/gct/blob/5826b06e1004717bad105ed9c41e65702bbba101/gridftp/server-lib/src/globus_gridftp_server_control_commands.c#L1970..L2002) - specifically lines 1994 and following - for the IPv4 case and  [/gridftp/server-lib/src/globus_gridftp_server_control_commands.c](https://github.com/gridcf/gct/blob/5826b06e1004717bad105ed9c41e65702bbba101/gridftp/server-lib/src/globus_gridftp_server_control_commands.c#L2095..L2150) - specifically lines 2145 and following  - for the IPv6 case).

****

Back to the actual issue: I would first avoid the segfaults (maybe with what I described in https://github.com/gridcf/UberFTP/issues/11#issuecomment-690479503 at the end) and then cope with what I described here further above. What do you think about that?

**Comment by fscheiner** [comment]
**Correction:**
If a SPAS response with IPv4 address(es) (contains commas (`,`) as delimiters in the response) is received it is parsed in [lines 3413 to 3444 of `_f_parse_addrs()`](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3414..L3444), if a SPAS response with IPv6 addresses (contains pipes (`|`) as delimiters in the response) is received it is parsed in [lines 3448 to 3511 of `_f_parse_addrs()`](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3448..L3511). That's the reason, why the code "only" expects the RFC2428 format for SPAS responses it should parse. To me these parts look correct now, apart from not anticipating "delayed passive", but this can be worked around [as written earlier](https://github.com/gridcf/UberFTP/issues/11#issuecomment-694258555). An actual implementation to support "delayed passive" can be added later then.

**Comment by msalle** [comment]
Ok, after reading your response I had a better look and I think indeed that my fixes should be kind of ok. I still don't like the code, but at least it seems a lot more reliable. I left a few TODOs in. There should actually be more...
Unfortunately I don't have a system to test against, I did test manually though (changing the response from the server inside gdb).
I don't know how a multi-entry response according to RFC2428 would look like, so that hasn't been tested.

**Comment by fscheiner** [comment]
@msalle 
> Ok, after reading your response I had a better look and I think indeed that my fixes should be kind of ok. I still don't like the code, but at least it seems a lot more reliable. I left a few TODOs in. There should actually be more...

I have a few ideas, but maybe an "active" C programmer should actually implement these:

* For [line 3451](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3451), a `grep -nri errno *` in a locally 
cloned UberFTP repo returns uses of `errno` throughout `uberftp`, e.g. like so:

```
fptr = fopen(urlfile, "r");
if (fptr == NULL)
{
	fprintf(stderr, 
	        "Failed to open the URL file: %s\n", 
	        strerror(errno));
	exit(1);
}
```

...or maybe better like so:

```
o_fprintf(stderr,
          DEBUG_ERRS_ONLY,
          "Failed to launch shell process: %s\n",
          strerror(errno));
```
...so it's only visible in debug mode. OTOH, why hold back for `ENOMEM`. I just don't know for sure if it is good style to just write to `stderr` from inside a sub function of a sub module. I think for BASH I'd just do that. ;-)

* for [line 3492](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3492) I'd just move the default case implementation of the following switch statement up and (1) execute that if `token[0]` is empty for "standard" RFC2428 responses and (2) execute the line with `atoi()` and the - now shortened - switch statement if it's not.

> Unfortunately I don't have a system to test against, I did test manually though (changing the response from the server inside gdb).
> I don't know how a multi-entry response according to RFC2428 would look like, so that hasn't been tested.

I'll setup a local IPv6 testbed for future testing, but if you like to give it a try inside gdb, a multi-entry response with RFC2428 address format should look like for example:
```
229-Entering Striped Passive Mode.
 |2|70dd:c42b:7eeb:724d:3c6b:85a8:a4f0:60db|20001|
 |2|68b9:5556:aa93:fba9:760f:6048:4032:5a14|20001|
 |2|bcc3:068a:206e:85b4:4c93:7b1e:ea86:841a|20001|
 |2|90ea:5c99:fa58:e9fb:85af:5035:c04e:40ec|20001|
229-end
```
...IIUIC according to [gridcf/gct/gridftp/server-lib/src/globus_gridftp_server_control_commands.c](https://github.com/gridcf/gct/blob/5826b06e1004717bad105ed9c41e65702bbba101/gridftp/server-lib/src/globus_gridftp_server_control_commands.c#L2095..L2150).

**Comment by fscheiner** [comment]
@msalle 
> > Unfortunately I don't have a system to test against, I did test manually though (changing the response from the server inside gdb).
> > I don't know how a multi-entry response according to RFC2428 would look like, so that hasn't been tested.
> 
> I'll setup a local IPv6 testbed for future testing, but if you like to give it a try inside gdb, a multi-entry response with RFC2428 address format should look like for example:
> 
> ```
> 229-Entering Striped Passive Mode.
>  |2|70dd:c42b:7eeb:724d:3c6b:85a8:a4f0:60db|20001|
>  |2|68b9:5556:aa93:fba9:760f:6048:4032:5a14|20001|
>  |2|bcc3:068a:206e:85b4:4c93:7b1e:ea86:841a|20001|
>  |2|90ea:5c99:fa58:e9fb:85af:5035:c04e:40ec|20001|
> 229-end
> ```
> 
> ...IIUIC according to [gridcf/gct/gridftp/server-lib/src/globus_gridftp_server_control_commands.c](https://github.com/gridcf/gct/blob/5826b06e1004717bad105ed9c41e65702bbba101/gridftp/server-lib/src/globus_gridftp_server_control_commands.c#L2095..L2150).

Just checked the response to `SPAS` with a GridFTP service using IPv6 addresses and indeed it looks like that also in reality.

****

Interesting side fact: `globus-url-copy` (with `-ipv6` used) actually sent `SPAS 2` to the GridFTP's PI, which "could" configure the address family the server should use for the response. But this is actually not defined in https://gridcf.org/gct-docs/api/latest/globus_ftp_extensions.html#sec_SPAS for some reason.
